name: build_docker_image

on:
  workflow_run:
    workflows: [ "test" ]
    types:
      - completed

jobs:
  build_docker_image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: davidsmith3
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Create .env
        run: touch .env

      - name: Set .env variables
        run: |
          echo "DOCKER_IMAGE=davidsmith3/cli-tools" >> .env
          echo "DOCKER_IMAGE_TAG=latest" >> .env

      - name: Build
        run: sh dh build

      - name: Push
        run: sh dh push